- hosts: all
  remote_user: root
  vars:
    repo_root: /var/www
    webmaster_email: webmaster@cucb.co.uk
    docker_compose_files:
      - docker-compose.prod.yml
    email_domain_name: dev.cucb.co.uk # TODO make this dynamic
  tasks:
    - name: Configure and run server
      include_role:
        name: "{{ item }}"
      loop:
        - install-dependencies
        - setup-global-environment
        - update-code
        - create-env-file
        - configure-timezone
        - configure-cron
        - download-documents
        - update-and-run-docker