stages:
  - test

test:
  image: docker:latest

  variables:
    DOCKER_DRIVER: overlay

  services:
    - docker:dind

  before_script:
    - docker info
    - apk add docker-compose

  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --exit-code-from cypress
