version: "3.6"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  cypress:
    volumes:
      - ./node_modules:/root/site/node_modules/
      - ./cypress_cache:/root/.cache/Cypress
    environment:
      PERCY_TOKEN: ${PERCY_TOKEN}
      PG_PASSWORD: postgrespassword
    command: >
      bash -c "cd /root/site; npm install; chmod a+x wait-for-it.sh; npm run test:ci"
