version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_restore:/backups
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  sveltekit:
    image: $DEPLOY_REGISTRY/cucb/sveltekit:slim
    environment:
      PG_USER: postgres
      PG_HOST: postgres
      PG_DATABASE: postgres
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SEND_ADDRESS: webmaster@cucb.co.uk
      VITE_HCAPTCHA_SITE_KEY: ${HCAPTCHA_SITE_KEY}
      EMAIL_SSL: "true"
      EMAIL_PORT: 587
      HCAPTCHA_SITE_KEY: ${HCAPTCHA_SITE_KEY}
      HCAPTCHA_SECRET: ${HCAPTCHA_SECRET}
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./static:/usr/src/app/static
      - ${BLOCK_STORAGE}/images:/usr/src/app/images
    restart: always
    command: "node build"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  caddy:
    image: caddy:latest
    restart: always
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./Caddyfile.lib:/etc/caddy/Caddyfile.lib
      - ${BLOCK_STORAGE}/certs:/root/.caddy/certs
      - ./static/static:/srv/static
      - ${BLOCK_STORAGE}/images:/srv/images
      - ./docs:/srv/docs
      - caddy_config:/config
      - caddy_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  db_data:
  caddy_config:
  caddy_data:
