version: "3.6"

services:
  postgres:
    image: postgres:12
    restart: always
    env_file: .env.development
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_restore:/backups
    ports:
      - "5432:5432"
  caddy:
    image: caddy:latest
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./Caddyfile.lib:/etc/caddy/Caddyfile.lib
      - ./static/static:/srv/static
      - ./images:/srv/images
      - ./docs:/srv/docs
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  db_data:
  node_modules_2:
