version: "3.6"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  sveltekit:
    build:
      context: .
      dockerfile: ci.Dockerfile
    user: node:node
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      POSTGRES_PASSWORD: postgrespassword
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    command: >
      bash -c "cd /home/node/app; npm ci; npm run build; npm run start:ci"
