version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  sveltekit:
    build:
      context: .
      dockerfile: ci.Dockerfile
    user: node:node
    # volumes:
    #   - .:/home/node/app
    #   - node_modules_test:/home/node/app/node_modules/
    #   - cypress_cache_test:/home/node/app/.cache/Cypress
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      SESSION_SECRET: notarealsecret
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PUBLIC_HCAPTCHA_SITE_KEY: "10000000-ffff-ffff-ffff-000000000001"
      HCAPTCHA_SECRET: "0x0000000000000000000000000000000000000000"
      EMAIL_HOST: mailhog
      EMAIL_SEND_ADDRESS: webmaster@cucb.co.uk
      EMAIL_PORT: 1025
      EMAIL_SSL: "false"
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      SKIP_CHECK_ORIGIN: "true"
      PUBLIC_GOOGLE_MAPS_API_KEY: ${PUBLIC_GOOGLE_MAPS_API_KEY}
    command: >
      bash -c "cd /home/node/app; npm ci; npm run build; npm run start:ci"

  caddy:
    image: caddy:latest
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./Caddyfile.lib:/etc/caddy/Caddyfile.lib
      - ./static/static:/srv/static
      - ./images:/srv/images
      - ./docs:/srv/docs
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db_data_test:
  node_modules_test:
  cypress_cache_test:
