version: "3.6"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    environment:
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    ports:
      - "8080:8080"
  cypress:
    image: node:14
    user: "root"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "10000:10000"
    environment:
      PERCY_TOKEN: ${PERCY_TOKEN}
      CYPRESS_KEY: ${CYPRESS_KEY}
      PG_PASSWORD: postgrespassword
    command: >
      bash -c "cd /usr/src/app; npm install; npm run build; chmod a+x wait-for-it.sh; ./wait-for-it.sh graphql-engine:8080 -t 180 -- npm run start:ci"
