version: "3.6"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
  sapper:
    environment:
      PERCY_TOKEN: ${PERCY_TOKEN}
      PG_PASSWORD: postgrespassword
      SESSION_SECRET: sessionsecret
    volumes:
      - ./node_modules:/app/node_modules
    command: >
      bash -c "cd /app/cypress && npm install && cd .. && npm install && npm run test:ci"