version: "3.6"
services:
    postgres:
        image: postgres:12
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    graphql-engine:
        image: hasura/graphql-engine:v1.1.1.cli-migrations
        volumes:
            - ./hasura/migrations:/hasura-migrations
        depends_on:
            - "postgres"
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
            HASURA_GRAPHQL_AUTH_HOOK: http://cypress:4000/auth/hook
    cypress:
        image: cypress/base:10
        volumes:
            - .:/root/site
            - node_modules:/root/site/node_modules/
            - cypress_cache:/root/.cache/Cypress
        environment:
            GRAPHQL_REMOTE: http://graphql-engine:8080
            GRAPHQL_PATH: /v1/graphql
            SESSION_SECRET: somethingreallysecret
            PG_USER: postgres
            PG_HOST: postgres
            PG_DATABASE: postgres
            PG_PASSWORD: postgrespassword
            PG_PORT: 5432
        command: >
            bash -c "apt update && apt install -y postgresql-client; cd /root/site; npm install; npm run test"

volumes:
    db_data:
    node_modules:
    cypress_cache:
