version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_restore:/backups
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432" # exposed so cypress can connect
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2.cli-migrations-v2
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${PG_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://sapper:4000/auth/hook
    ports:
      - "8080:8080"
  sapper:
    image: node:13
    environment:
      GRAPHQL_REMOTE: http://graphql-engine:8080
      GRAPHQL_PATH: /v1/graphql
      PG_USER: postgres
      PG_HOST: postgres
      PG_DATABASE: postgres
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD}
    volumes:
      - .:/root/site
      - node_modules:/root/site/node_modules/
    ports:
      - "4000:4000"
      - "10000:10000"
    command: >
      bash -c "cd /root/site; npm install; chmod a+x ./wait-for-it.sh; npm run dev"
volumes:
  db_data:
  node_modules:
