- name: Generate secrets
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: "{{ secret_name }}"
    value: "{{ lookup('password', '/dev/null length=40') }}"
  loop:
    - PG_PASSWORD
    - SESSION_SECRET
  loop_control:
    loop_var: secret_name

- name: Find block storage location, mounting if necessary
  include_role:
    name: detect-mounted-block-storage

- name: Create block storage variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: BLOCK_STORAGE
    value: "{{ block_storage.files[0].path }}"
  when: block_storage.matched == 1

- name: Create hcaptcha secret variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: HCAPTCHA_SECRET
    value: "{{ hcaptcha_secret }}"

- name: Create email username variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: EMAIL_USERNAME
    value: "{{ email_username }}"

- name: Create email password variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: EMAIL_PASSWORD
    value: "{{ email_password }}"

- name: Create email host variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: EMAIL_HOST
    value: "{{ email_host }}"

- name: Create calendar secret variable
  include_role:
    name: create-variable
  vars:
    env_file: "{{ repo_root }}/.env"
    name: CALENDAR_SECRET
    value: "{{ calendar_secret }}"
