import type { EntityManager } from "@mikro-orm/postgresql";
import { Seeder } from "@mikro-orm/seeder";
import { Music } from "../lib/entities/Music.js";

export class MusicSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    await Promise.all([
      em.upsert(Music, {
        id: "2875",
        title: "Dusty Windowsills",
        filename: "DustyWindowsills",
        type: "8",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2876",
        title: "Peggy's Nettles",
        filename: "PeggysNettles",
        type: "8",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2877",
        title: "Trip to Durrow",
        filename: "TripToDurrow",
        type: "9",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2878",
        title: "Ashokan Farewell",
        filename: "AshokanFarewell",
        type: "12",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2879",
        title: "Inisheer",
        filename: "Inisheer",
        type: "12",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2880",
        title: "Morning Star, The",
        filename: "MorningStar",
        type: "6",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2881",
        title: "Uttoxeter Swing",
        filename: "UttoxeterSwing",
        type: "6",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2882",
        title: "Marches 1",
        filename: "Marches1",
        type: "5",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2883",
        title: "Marches 2",
        filename: "Marches2",
        type: "5",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2884",
        title: "Angus Polkas",
        filename: "Angus",
        type: "4",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2885",
        title: "Foxhunter's, The",
        filename: "Foxhunters",
        type: "7",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2886",
        title: "Whiskey Exiles",
        filename: "WhiskeyExiles",
        type: "7",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2887",
        title: "Auld Lang Syne",
        filename: "AuldLangSyne",
        type: "12",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2888",
        title: "Happy Birthday",
        filename: "HappyBirthday",
        type: "12",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2889",
        title: "Canadian Barn Dance",
        filename: "CanadianBarnDance",
        type: "10",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2890",
        title: "Dashing White Sergeant, The",
        filename: "DashingWhiteSergeant",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2891",
        title: "Gay Gordons",
        filename: "GayGordons",
        type: "5",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2892",
        title: "Special Dances",
        filename: "SpecialDances",
        type: "4",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2893",
        title: "Strip the Willow",
        filename: "StripTheWillow",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2894",
        title: "Belle Mere's",
        filename: "BelleMeresWaltz",
        type: "3",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2895",
        title: "Farquhar and Hettie's",
        filename: "FarquharAndHetties",
        type: "3",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2896",
        title: "Northumbrian Waltzes",
        filename: "NorthumbrianWaltzes",
        type: "3",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, { id: "2897", title: "Rosza", filename: "Rosza", type: "3", current: true, showTune: false }),
      em.upsert(Music, {
        id: "2898",
        title: "Animal Polkas",
        filename: "Animal",
        type: "4",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2899",
        title: "Oxo Reels",
        filename: "OxoReels",
        type: "4",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2900",
        title: "Scottish Reels 1",
        filename: "Scottish1",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2901",
        title: "Scottish Reels 5",
        filename: "Scottish5",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2902",
        title: "Shetland Molecule",
        filename: "ShetlandMolecule",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2903",
        title: "Shetland Reels 1",
        filename: "ShetlandReels",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2904",
        title: "Transatlantic Reels",
        filename: "Transatlantic",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2905",
        title: "Carol Gibson's",
        filename: "CarolGibsons",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2906",
        title: "Cat That Ate the Candle, The",
        filename: "CatThatAteTheCandle",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2907",
        title: "Cumberland Set",
        filename: "Cumberland",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2908",
        title: "Dance Above the Rainbow",
        filename: "DanceAboveTheRainbow",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2909",
        title: "Flora MacAulay's",
        filename: "FloraMacaulays",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2910",
        title: "Irish Jigs",
        filename: "IrishJigs",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, { id: "2911", title: "Jigs 1", filename: "Jigs1", type: "1", current: true, showTune: false }),
      em.upsert(Music, { id: "2912", title: "Jigs 2", filename: "Jigs2", type: "1", current: true, showTune: false }),
      em.upsert(Music, { id: "2913", title: "Jigs 3", filename: "Jigs3", type: "1", current: true, showTune: false }),
      em.upsert(Music, { id: "2914", title: "Jigs 4", filename: "Jigs4", type: "1", current: true, showTune: false }),
      em.upsert(Music, {
        id: "2915",
        title: "Pull the Knife",
        filename: "PullTheKnife",
        type: "1",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2916",
        title: "Double Flats",
        filename: "DoubleFlats",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2917",
        title: "Killin' Clocks",
        filename: "KillinClocks",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2918",
        title: "Mostly English Reels",
        filename: "MostlyEnglish",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2919",
        title: "Mostly Irish Reels",
        filename: "MostlyIrish",
        type: "2",
        current: true,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2920",
        title: "Holm Sweet Home",
        filename: "HolmSweetHome",
        type: "16",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2921",
        title: "Horizonto",
        filename: "Horizonto",
        type: "8",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2922",
        title: "Zycanthos Jig",
        filename: "Zycanthos",
        type: "1",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2923",
        title: "Congress",
        filename: "Congress",
        type: "2",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2924",
        title: "Islay in da Mornin'",
        filename: "IslayInDaMornin",
        type: "2",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2925",
        title: "Knockdhu",
        filename: "Knockdhu",
        type: "13",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2926",
        title: "Lovers' Reels",
        filename: "LoversReels",
        type: "2",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2927",
        title: "Maggie's Pancakes",
        filename: "MaggiesPancakes",
        type: "2",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2928",
        title: "Tee Reels",
        filename: "TeeReels",
        type: "2",
        current: true,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2929",
        title: "79th's Farewell to Gibraltar",
        filename: "79thsFarewelltoGibraltar",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2930",
        title: "Astley's Ride",
        filename: "AstleysRide",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2931",
        title: "Bessie the Beauty of Rossinare Hill",
        filename: "BessieTheBeautyOfRossinareHill",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2932",
        title: "Chicken Reel, The",
        filename: "ChickenReel",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2933",
        title: "Ciaran Tourish",
        filename: "CiaranTourish",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2934",
        title: "Circassian Circle",
        filename: "CircassianCircle",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2935",
        title: "Drunken Piper, The",
        filename: "DrunkenPiper",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2936",
        title: "English Polkas",
        filename: "EnglishPolkas",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2937",
        title: "Flatworld",
        filename: "Flatworld",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2938",
        title: "Gay Gordons 2 (The Fairly Cheerful Gordons)",
        filename: "GayGordons2",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2939",
        title: "Granny in the Attic",
        filename: "GrannyInTheAttic",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2940",
        title: "Helen Black of Inveran",
        filename: "HelenBlackOfInveran",
        type: "5",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2941",
        title: "Highland Schottische",
        filename: "HighlandScottische",
        type: "10",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2942",
        title: "Hornpipes 2",
        filename: "Hornpipes2",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2943",
        title: "Irish Jigs 1",
        filename: "IrishJigs1",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2944",
        title: "Istanbul",
        filename: "Istanbul",
        type: "16",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2945",
        title: "King of the Fairies",
        filename: "KingOfTheFairies",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2946",
        title: "La Russe",
        filename: "LaRusse",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2947",
        title: "Lonesome Wren",
        filename: "LonesomeWren",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2948",
        title: "Margaret's",
        filename: "Margarets",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2949",
        title: "Monaghan Twist, The",
        filename: "MonaghanTwist",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2950",
        title: "Northumbrian Waltzes 2",
        filename: "Northumbrian2",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2951",
        title: "Pride of Erin",
        filename: "PrideOfErin",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2952",
        title: "Rakes of Clonmel, The",
        filename: "RakesOfClonmel",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2953",
        title: "Random Jigs",
        filename: "Random",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2954",
        title: "Reels McCoy, The",
        filename: "ReelsMcCoy",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2955",
        title: "Road Together, The",
        filename: "RoadTogether",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2956",
        title: "Scottish Reels 2",
        filename: "Scottish2",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2957",
        title: "Scottish Reels 4",
        filename: "Scottish4",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2958",
        title: "Scottish Reels 5 (Pre-2017)",
        filename: "Scottish5OLD",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2959",
        title: "Scottish Reels 6",
        filename: "Scottish6",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2960",
        title: "Scottish Reels 7",
        filename: "Scottish7",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2961",
        title: "Shetland Reels 1 (Pre-2017)",
        filename: "Shetland1OLD",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2962",
        title: "Shetland Reels 2",
        filename: "Shetland2",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2963",
        title: "Shetland Molecule (Pre-2017)",
        filename: "ShetlandMoleculeOLD",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2964",
        title: "Si Beag Si Mhor",
        filename: "SiBeagSiMor",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2965",
        title: "Sleepy Maggie",
        filename: "SleepyMaggie",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2966",
        title: "Special Dances",
        filename: "SpecialDances",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2967",
        title: "Spellan the Fiddler",
        filename: "SpellanTheFiddler",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2968",
        title: "Strip the Willow 1",
        filename: "StripTheWillow1",
        type: "7",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2969",
        title: "Strip the Willow 2",
        filename: "StripTheWillow2",
        type: "7",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2970",
        title: "Sweets of May",
        filename: "SweetsOfMay",
        type: "8",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2971",
        title: "Tabletop Mountain",
        filename: "TabletopMountain",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2972",
        title: "Welsh Jigs",
        filename: "WelshJigs",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2973",
        title: "Whinham's Jig",
        filename: "Whinhams",
        type: "1",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2974",
        title: "Baccapipes",
        filename: "Baccapipes",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2975",
        title: "Eightsome Reel",
        filename: "EightsomeReel",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2976",
        title: "For the Love of Music",
        filename: "ForTheLoveOfMusic",
        type: "7",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2977",
        title: "French Waltzes",
        filename: "FrenchWaltzes",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2978",
        title: "Green Loch",
        filename: "GreenLoch",
        type: "12",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2979",
        title: "Hornpipes 1",
        filename: "Hornpipes1",
        type: "6",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, { id: "2980", title: "Jigs 5", filename: "Jigs5", type: "1", current: false, showTune: false }),
      em.upsert(Music, {
        id: "2981",
        title: "Kissing Pilgrims in the Kitchen",
        filename: "KissingPilgrimsInTheKitchen",
        type: "8",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2982",
        title: "Night on the Gin, A",
        filename: "NightOnTheGin",
        type: "8",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2983",
        title: "Pick and Mix Waltzes",
        filename: "PickAndMixWaltzes",
        type: "3",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2984",
        title: "Scottish Reels 3",
        filename: "Scottish3",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2985",
        title: "Turkey's Cakewalk",
        filename: "TurkeysCakewalk",
        type: "2",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2986",
        title: "Go Captain Bing",
        filename: "GoCaptainBing",
        type: "4",
        current: false,
        showTune: false,
      }),
      em.upsert(Music, {
        id: "2987",
        title: "Strathspey and Reel",
        filename: "StrathspeyAndReel",
        type: "13",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2988",
        title: "Waterman's",
        filename: "Watermans",
        type: "15",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2989",
        title: "Wizard's Walk, The",
        filename: "WizardsWalk",
        type: "2",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2990",
        title: "Zycanthos Jig (5/8 version)",
        filename: "Zycanthos58",
        type: "14",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2991",
        title: "Ben's Nightmare",
        filename: "BensNightmare",
        type: "2",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2992",
        title: "Da Auld Resting Chair",
        filename: "DaAuldRestingChair",
        type: "12",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2993",
        title: "Dawn Chorus",
        filename: "DawnChorus",
        type: "2",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2994",
        title: "Foreland Point",
        filename: "ForelandPoint",
        type: "3",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2995",
        title: "Ragnarök",
        filename: "Ragnarok",
        type: "11",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2996",
        title: "Slow Airs",
        filename: "SlowAirs",
        type: "12",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2997",
        title: "Slow Airs 2",
        filename: "SlowAirs2",
        type: "12",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2998",
        title: "Catharsis",
        filename: "Catharsis",
        type: "2",
        current: false,
        showTune: true,
      }),
      em.upsert(Music, {
        id: "2999",
        title: "Warning Seven Eight!",
        filename: "Warning78",
        type: "15",
        current: false,
        showTune: true,
      }),
    ]);
  }
}
