version: "3.6"
services:
  cypress:
    image: $DEPLOY_REGISTRY/cucb/website:latest
    volumes:
      - app:/usr/src/app
      - ./static:/usr/src/app/static
    command: >
      bash -c "chmod a+x wait-for-it.sh; ./wait-for-it.sh graphql-engine:8080 -t 180 -- npm run test:ci:prod"

volumes:
  app:
