version: "3.6"
services:
  cypress:
    image: $DEPLOY_REGISTRY/cucb/website:latest
    command: >
      bash -c "chmod a+x wait-for-it.sh; ./wait-for-it.sh graphql-engine:8080 -t 180 -- npm run test:ci:prod"
