version: "3.6"
services:
  cypress:
    image: $DEPLOY_REGISTRY/cucb/website:latest
    volumes:
      - app:/usr/src/app
      - ./static:/usr/src/app/static
      - ./wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - ./cypress.json:/usr/src/app/cypress.json
      - ./cypress:/usr/src/app/cypress
    command: >
      bash -c "apt-get update && \
               apt-get install --no-install-recommends -y \
               libgtk2.0-0 \
               libgtk-3-0 \
               libnotify-dev \
               libgconf-2-4 \
               libgbm-dev \
               libnss3 \
               libxss1 \
               libasound2 \
               libxtst6 \
               xauth \
               xvfb \
               # install Chinese fonts
               # this list was copied from https://github.com/jim3ma/docker-leanote
               fonts-arphic-bkai00mp \
               fonts-arphic-bsmi00lp \
               fonts-arphic-gbsn00lp \
               fonts-arphic-gkai00mp \
               fonts-arphic-ukai \
               fonts-arphic-uming \
               ttf-wqy-zenhei \
               ttf-wqy-microhei \
               xfonts-wqy \
               && rm -rf /var/lib/apt/lists/*; npx cypress install; chmod a+x wait-for-it.sh; ./wait-for-it.sh graphql-engine:8080 -t 180 -- npm run test:ci:prod"

volumes:
  app:
