- name: Configure nullmailer domain
  copy:
    dest: /etc/mailname
    content: cucb.co.uk

- name: Install dependencies
  apt:
    name:
      - docker-compose
      - npm
      - nodejs
      - duplicity
      - python3-pip
      - cronic
      - git
      - cockpit
      - nullmailer
    update_cache: yes

- name: Configure nullmailer SMTP settings
  copy:
    dest: /etc/nullmailer/remotes
    content: "{{ email_host }} smtp --auth-login --user={{ email_username }} --pass={{ email_password }}"

- name: Install Python Dropbox sdk
  pip:
    name: dropbox
