- name: Configure nullmailer domain
  copy:
    dest: /etc/mailname
    content: cucb.co.uk

- name: Install dependencies
  apt:
    name:
      - docker-compose
      - npm
      - nodejs
      - duplicity
      - python3-pip
      - cronic
      - git
      - cockpit
      - nullmailer
      - lame
      - vorbis-tools
      - ghostscript
      - timidity
      - abcm2ps
      - abcmidi # abc2abc and abcmidi
      - pdftk-java
    update_cache: yes

- name: Configure nullmailer SMTP settings
  copy:
    dest: /etc/nullmailer/remotes
    content: "{{ email_host }} smtp --auth-login --user={{ email_username }} --pass={{ email_password }}"

- name: Install Python Dropbox sdk
  pip:
    name: dropbox

- name: Ensure bin directory exists
  file:
    name: "{{ repo_root }}/bin"
    state: directory

- name: Copy music page dependencies to bin folder
  copy:
    src: /usr/bin/{{ item }}
    dest: "{{ repo_root }}/bin/{{ item }}"
    remote_src: true
  with_items:
    - abc2abc
    - abc2midi
    - abcm2ps
    - lame
    - oggenc
    - pdftk
    - ps2pdf
    - timidity
