- name: "Set mailto address for cron"
  cronvar:
    name: MAILTO
    value: "{{ webmaster_email }}"

- name: "Cron job: Backup each night"
  cron:
    name: Nightly backup
    minute: "0"
    hour: "1"
    job: "cd {{ repo_root }} && cronic ./deploy/backup.sh"

- name: "Cron job: Start server on reboot"
  cron:
    name: Start server on reboot
    special_time: reboot
    job: "cd {{ repo_root }} && cronic ./deploy/start.sh"
