name: CUCB-Website-Deploy

on:
  push:
    branches:
      - master
      - feature/gh-deploy

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('package*.json') }}

      - name: Login to registry
        run: docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

      - name: Build and tag image
        run: |
          echo "HCAPTCHA_SITE_KEY=$HCAPTCHA_SITE_KEY" >> build.env
          docker run -v "$PWD":/usr/src/app -w /usr/src/app node:12 npm install
          docker build -t $CI_REGISTRY/cucb/website:latest -f deploy/Dockerfile .

      - name: Push image to registry
        run: docker push $CI_REGISTRY/cucb/website:latest
  test:
    name: Test site
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to registry
        run: docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

      - name: Test image
        run: docker-compose -f docker-compose.test.yml -f docker-compose.ci.yml -f deploy/docker-compose-ci-master.yml up --exit-code-from=cypress
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-output
          path: |
            cypress/videos/**/*.mp4
            cypress/screenshots/**/*.png

env:
  CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
  CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
  CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
  DEPLOY_REGISTRY: ${{ secrets.CI_REGISTRY }}
