name: Build/Test/Deploy

on:
  push:

jobs:
  build:
    if: ${{ github.ref=='refs/heads/master' || github.ref=='refs/heads/feature/gh-deploy' }}
    name: Build and push docker image for deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('package*.json') }}

      - name: Login to registry
        run: docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

      - name: Build and tag image
        run: |
          echo "HCAPTCHA_SITE_KEY=$HCAPTCHA_SITE_KEY" >> build.env
          docker run -v "$PWD":/usr/src/app -w /usr/src/app node:12 npm install
          docker build -t $CI_REGISTRY/cucb/website:latest -f deploy/Dockerfile .

      - name: Push image to registry
        run: docker push $CI_REGISTRY/cucb/website:latest
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Start server and run tests
        run: docker-compose -f docker-compose.test.yml -f docker-compose.ci.yml up --exit-code-from=cypress
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-output
          path: |
            cypress/videos/**/*.mp4
            cypress/screenshots/**/*.png
